services:
  apache:
    build: ./apache
    ports:
      - "8081:80"
    volumes:
      - ./apache/spa:/usr/local/apache2/htdocs/
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

