apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-9-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-9-rust
  template:
    metadata:
      labels:
        app: pr-9-rust
    spec:
      containers:
      - name: rust
        image: pr-9-rust:latest
        ports:
        - containerPort: 8081
